@startuml AppDiagram
@@startmindmap 功能结构图
* App
** 文本文件列表(document,不包含document/assert)

*** 文件和文件夹显示
**** 文件夹进入和返回(可以查看文件夹里面的文件)

*** 文件添加、删除、改名、移动

*** 文件夹添加、删除、改名

*** 搜索(当前文件夹)、滑动

*** 文件内容查看(纯文本文件、pdf)
**** 内容查找

**** 内容编辑
***** 复制、粘贴、保存(基础功能)

***** 插入图片路径(md等文件,通过图片文件夹的文件进行添加)

***** 预览(对于md、html,里面图片的路径读取图片文件夹)

***** 分享至其他软件

***** 导出(md->html,html->pdf)


** 图片文件列表(document/assert)
*** 创建文件夹

*** 导入图片(从相册导入)

*** 查看图片


** 设置(暂时没有写保存功能)
*** 颜色改变(深浅色)

*** 字体行距修改

@@endmindmap
@enduml
